# Generated by Django 5.2.6 on 2025-09-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_doctor_username_alter_patient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
