# Generated by Django 5.2.6 on 2025-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_doctor_id_remove_patient_id_patient_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='Doctor Username Default', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
