# Generated by Django 5.2.6 on 2025-09-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
