# Generated by Django 5.2.6 on 2025-09-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_doctor_full_name_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='Userpassword', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='Userpassword', max_length=128, null=True),
        ),
    ]
