# Generated by Django 5.2.6 on 2025-09-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, default='Userpassword', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, default='Userpassword', max_length=128, null=True),
        ),
    ]
