# Generated by Django 5.2.6 on 2025-09-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_doctor_password_alter_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
