# Generated by Django 5.2.6 on 2025-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
