# Generated by Django 5.2.6 on 2025-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_videos', '0002_alter_videos_description_alter_videos_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='mini_description',
            field=models.TextField(blank=True),
        ),
    ]
