# Generated by Django 5.2.6 on 2025-09-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserVitals', '0001_initial'),
        ('Users', '0010_doctor_full_name_patient_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='Users.patient'),
        ),
    ]
