# Generated by Django 5.2.6 on 2025-09-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserVitals', '0003_alter_uservitals_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservitals',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservitals',
            name='diastolic_blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservitals',
            name='heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservitals',
            name='oxygen_sat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservitals',
            name='steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uservitals',
            name='systolic_blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
