# Generated by Django 5.2.6 on 2025-09-29 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserVitals', '0004_uservitals_calories_and_more'),
        ('Users', '0010_doctor_full_name_patient_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.patient')),
            ],
        ),
    ]
