# Generated by Django 5.2.6 on 2025-11-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserVitals', '0005_userbpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
